name: Deploy Docusaurus Site

on:
  push:
    tags:
      - "*"  # Change this to your default branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      uses: actions/checkout@v3

      - name: Download artifact from the latest workflow run
        uses: actions/download-artifact@v4
        with:
          name: openapi.json  # Name of the artifact you want to download
          path: ./docs/openapi/openapi.json  # Directory where the artifact will be downloaded

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Ensure this matches the Node.js version required by Docusaurus

      - name: Install dependencies
        working-directory: ./docs  # Change to the directory where package.json is located
        run: npm install

      - name: Build Docusaurus site
        working-directory: ./docs  # Change to the directory where package.json is located
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build   # Ensure this matches the build output directory of Docusaurus
