name: Update Docusaurus

on:
  push:
    branches:
      - "*"

jobs:
  update-doc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        rm ./docs/openapi/openapi.json

    - uses: robinraju/release-downloader@v1
      with:
      repository: ''
      latest: true
      preRelease: false
      fileName: 'openapi.json'

      # Relative path under $GITHUB_WORKSPACE to place the downloaded file(s)
      # It will create the target directory automatically if not present
      # eg: out-file-path: "my-downloads" => It will create directory $GITHUB_WORKSPACE/my-downloads
      out-file-path: 'docs/openapi'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # Ensure this matches the Node.js version required by Docusaurus

    - name: Install dependencies
      working-directory: ./docs  # Change to the directory where package.json is located
      run: npm install

    - name: Build Docusaurus site
      working-directory: ./docs  # Change to the directory where package.json is located
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build   # Ensure this matches the build output directory of Docusaurus
